dist: xenial
language: c++

jobs:
  include:
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-cplusplus"
  - os: linux
    addons:
      apt:
        packages:
        - libatomic-ops-dev
    env:
    - MAKEFILE_TARGETS="distcheck"
    - GC_REAL_VERSION=7.2n
    - AO_SRC_VER=v7.2i
  - os: linux
    env:
    - MAKEFILE_TARGETS="dist"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    addons:
      apt:
        packages:
        - libatomic-ops-dev
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-cplusplus"
    - NO_CLONE_LIBATOMIC_OPS=true
  - os: linux
    addons:
      apt:
        packages:
        - libatomic-ops-dev
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-gc-assertions --enable-cplusplus"
    - NO_CLONE_LIBATOMIC_OPS=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-gc-assertions --enable-handle-fork --enable-cplusplus"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-gc-debug --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-munmap --enable-cplusplus"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-handle-fork --enable-munmap --enable-cplusplus --disable-shared --enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--disable-gc-debug --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-large-config --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-large-config --enable-cplusplus"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-large-config --disable-munmap"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-large-config --enable-munmap --enable-cplusplus --enable-gc-assertions --enable-static"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--enable-redirect-malloc --disable-threads"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--enable-redirect-malloc --enable-cplusplus --disable-threads"
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--enable-redirect-malloc --enable-gc-debug --enable-cplusplus --enable-gc-assertions"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: clang
    env:
    - CONF_OPTIONS="--disable-static --disable-threads --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: linux
    compiler: gcc
    env:
    - CONF_OPTIONS="--disable-static --disable-threads --enable-cplusplus"
    - WORKAROUND_ACLOCAL_MISSING=true
  - os: osx
    env:
    - CONF_OPTIONS="--disable-static --disable-threads --enable-cplusplus"

before_install:
- if [[ "$MAKEFILE_TARGETS" == *"dist"* ]]; then
    autoconf --version;
    automake --version;
    m4 --version;
    libtool --version || true;
    pkg-config --version;
  fi
- if [[ "$MAKEFILE_TARGETS" == "" ]]; then MAKEFILE_TARGETS="check"; fi

install:
- if [[ "$NO_CLONE_LIBATOMIC_OPS" != true ]]; then
    if [[ "$AO_SRC_VER" == "" ]]; then AO_SRC_VER="release-7_2"; fi;
    git clone --depth=50 https://github.com/ivmai/libatomic_ops.git
              -b $AO_SRC_VER;
  fi
- if [[ "$WORKAROUND_ACLOCAL_MISSING" == true ]]; then
    autoreconf --force --install;
  fi

script:
- ./configure $CONF_OPTIONS
- make -j $MAKEFILE_TARGETS
- if [[ "$GC_REAL_VERSION" != "" ]]; then
    tar xf gc-*.tar.gz;
    rm gc-*.tar.*;
    (cd gc-*; ln -s ../libatomic_ops);
    tar cf gc-$GC_REAL_VERSION.tar --dereference
        --exclude=".*" --exclude="*.yml" gc-*/;
    gzip --best --verbose gc-*.tar;
  fi

deploy:
  provider: releases
  api_key:
    secure: j1HkSD5hyYFo//XzPemojLk6iBT+T9+PwktxtDOwdasR0lOvPyBS2k/RbBZp+amDna/40efTg2WVI8BEfpRMV8+QoYGVoTWCKCaxFCHMfSZdsPLYsHpeqp7PBh3sFX6iuQuZkRGXHNeG8cLHTTw1TatrEBU/vTZXItYKmOJH8WnlwwkiVXKQ3BvU9EJjFB1OJX9PArBXgoHjDcgi6D1kL6ErsraU9nwnaBNRFx5Tpvz/fXZDwjzMnGcxeu02zhVC37mFDd6VbKom8Pm28u4NjYLLhjdICexc0BaVC0kr3+usJytyMtWMRm6LN4kFievOntHZOEAtuU6/E0Bg8wnB8FX8vXaytb+eUVtcfS/n/x6ykgPtKHrCnWEP8nnruW/3qRExxSBASyAwBceJK+yyzVBtQudK4YZnBXUWkFfsc9pPiauUDXkYlUgvVyb3rXvJTvjdiIle194GtRsCQsGKxCZiI6jMB/wRQAA9AgcSb3FpRTqkVPEUT3Gnn0xT+Y0QLJBBm4eAG8qWoEuMMAW8lAVvfHdZh3AnnIvqONvc2dk7kq5EZyhUPTFFDxZGnXWzIwY7Nm9QkUOdvb9t+RsnoTwBL4hSD4/T1CgW/hULQ7cuiwtK/E+8r5C1VES5/I20qkwfTGwKQchdR6lOLO7YM4VlHfNbEUe/wsE3PBh0ekc=
  file: gc-*.tar.gz
  file_glob: true
  on:
    condition: $MAKEFILE_TARGETS = distcheck
    repo: ivmai/bdwgc
    tags: true
